version: '3.8'

services:
  # Main development service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Test service for running automated tests
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - DEBUG=false
    command: npm run test
    depends_on:
      app:
        condition: service_healthy

  # Performance testing service
  perf:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
      - ./tests/performance/results:/app/tests/performance/results
    environment:
      - NODE_ENV=test
      - PERFORMANCE_TEST=true
    command: python3 tests/performance/benchmark_3a2c2412-e1a1-455b-ad87-0514e8d942fe.py
    depends_on:
      app:
        condition: service_healthy

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  node_modules: