version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - CHROME_BIN=/usr/bin/chromium-browser
      - PERFORMANCE_MONITORING=true
      # Test configuration
      - TEST_BROWSER=chrome
      - TEST_COVERAGE_THRESHOLD=80
      - TEST_TIMEOUT=30000
      - TEST_RETRIES=2
      # Performance thresholds
      - PERF_MAX_HEAP=512
      - PERF_MAX_FPS_DROP=5
      - PERF_MAX_FRAME_TIME=16.67
    command: npm test
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Chrome container for running browser tests
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 15s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  node_modules:

networks:
  default:
    name: space-invaders-test
    driver: bridge