# Space Invaders Test Environment Configuration
# Purpose: Provides isolated testing environment with necessary dependencies
version: '3.8'

services:
  # Main test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - JEST_JUNIT_OUTPUT_DIR=/app/test-results
      - JEST_JUNIT_OUTPUT_NAME=junit.xml
      # Browser testing configuration
      - BROWSER_TESTS_ENABLED=true
      - BROWSER_HEADLESS=true
      # Performance testing thresholds
      - PERF_TEST_FPS_THRESHOLD=60
      - PERF_TEST_MEMORY_THRESHOLD=100MB
    command: >
      sh -c "
        npm run test:unit &&
        npm run test:integration &&
        npm run test:e2e &&
        npm run test:performance
      "

  # Browser testing service using Selenium
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Performance monitoring service
  performance-monitor:
    image: grafana/k6:latest
    volumes:
      - ./tests/performance:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb

  # Metrics storage
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Test results visualization
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  node_modules:
  influxdb_data:
  grafana_data:

networks:
  default:
    name: space-invaders-test
    driver: bridge